package mx.com.bmt.bpms.entity;
// Generated 05-jun-2015 12:00:04 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais")
   public class Pais  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Date fecharegistro;

    public Pais() {
    }

	
    public Pais(int id) {
        this.id = id;
    }
    public Pais(int id, String descripcion, Date fecharegistro) {
       this.id = id;
       this.descripcion = descripcion;
       this.fecharegistro = fecharegistro;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecharegistro", length=13)
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


